// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using UnityEngine;
using Common.Model.Item;
using Controller.Generator;
using Controller.GameData;
using System.Collections.Generic;

namespace Logic
{
	public class GameInit : MonoBehaviour
	{
		void Start()
		{
			ItemDataManager.Instance.Init ();

			GeneratorItem click = ItemDataManager.Instance.GetGeneratorItem (1004);
			if (null != click) 
			{
				m_meetClick = new GeneratorController();
				m_meetClick.Context = click;

			}

			click = ItemDataManager.Instance.GetGeneratorItem (1005);
			if (null != click) 
			{
				m_wookClick = new GeneratorController();
				m_wookClick.Context = click;
			}

			click = ItemDataManager.Instance.GetGeneratorItem (1006);
			if (null != click) 
			{
				m_stoneClick = new GeneratorController();
				m_stoneClick.Context = click;
			}

			m_listResIDs.Add (101);			
			m_listResIDs.Add (102);
			m_listResIDs.Add (103);
			m_listResIDs.Add (104);
			m_listResIDs.Add (106);
		}

		void FixedUpdate()
		{
			GeneratorControllerMgr.Instance.Generate ();
		}

		void OnGUI()
		{
			if (GUILayout.Button ("Meet")) 
			{
				if(null != m_meetClick)
				{
					m_meetClick.Generate();
				}
			}

			if (GUILayout.Button ("Wook")) 
			{
				if(null != m_wookClick)
				{
					m_wookClick.Generate();
				}
			}

			if (GUILayout.Button ("Stone")) 
			{
				if(null != m_stoneClick)
				{
					m_stoneClick.Generate();
				}
			}

			GUILayout.BeginVertical ("box");

			for (int iIndex = 0; iIndex < m_listResIDs.Count; iIndex++) 
			{
				_DrawItem(m_listResIDs[iIndex]);
			}

			GUILayout.EndVertical ();
		}

		private void _DrawItem(int ID)
		{
			GUILayout.BeginHorizontal ();

			ResourceItem item = ItemDataManager.Instance.GetResourceItem (ID);
			if(null != item)
			{
				GUILayout.Label(string.Format("ResName: {0}", item.Name));
				GUILayout.Label(string.Format("Count : {0}", GameDataManager.Instance.GetResourceItemValue(ID)));
			}

			GUILayout.EndHorizontal ();
		}

		#region Memeber

		private GeneratorController m_meetClick = default(GeneratorController);
		private GeneratorController m_wookClick = default(GeneratorController);
		private GeneratorController m_stoneClick = default(GeneratorController);
		private List<int> m_listResIDs = new List<int> ();

		#endregion 
	}
}

