// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using UnityEngine;
using Common.Model.Item;
using MiniJSON;

public class TestController : MonoBehaviour
{
	void Start()
	{
		ItemDataManager.Instance.Init ();
	}
}