// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace Common.Model.Item
{
	public class ResourceItem
	{
		public override string ToString ()
		{
			return string.Format ("[ResourceItem] ID {0}, Name{1}, Icon {2}, Des {3}", ID, Name, Icon, Description);
		}

		public int ID = 0;
		public string Name = string.Empty;
		public string Icon = string.Empty;
		public string Description = string.Empty;
	}

	public class GeneratorItem
	{
		public override string ToString ()
		{
			return string.Format ("[GeneratorItem] ID {0}, Name{1}, Icon {2}, Des {3}", GeneratorID, Name, Icon, Des);
		}

		public int GeneratorID = 0;
		public string Name = string.Empty;
		public string Icon = string.Empty;
		public string Des = string.Empty;
		public int ConsumablesID = 0;
		public float ConsumablesCount1 = 0;
		public int ConsumablesID2 = 0;
		public float ConsumablesCount2 = 0;
		public int GeneratResID1 = 0;
		public float GeneratResCount1 = 0;
		public float Probability1 = 0.0f;
		public int GeneratResID2 = 0;
		public float GeneratResCount2 = 0;
		public float Probability2 = 0.0f;
	}


}

