// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace General.GeneralInterface
{
	public interface IGenerator
	{
		float Generate(float input, out float consume);
	}

	public interface IExchange
	{
		float Exchage(out float input);
	}

	public interface IController<T>
		where T : class
	{
		T Context 
		{
			get;
			set;
		}
	}

}

