// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using com.CommonUtility.Common;
using UnityEngine;

public class ResourceManager : TSingleton<ResourceManager>, IDisposable
{
	#region IDisposable implementation
	
	public void Dispose ()
	{
		//throw new NotImplementedException ();
	}
	
	public UnityEngine.Object LoadResource(string resPath)
	{
		UnityEngine.Object ret = null;
		if (m_dicRes.TryGetValue (resPath, out ret)) 
		{
			return ret;
		}
		
		ret = _LoadResouces (resPath);
		if (null != ret) 
		{
			m_dicRes.Add(resPath, ret);
		}
		
		return ret;
	}
	
	#endregion
	
	#region Private Functions
	
	private UnityEngine.Object _LoadResouces(string resPath)
	{
		return Resources.Load (resPath);
	}
	
	#endregion 
	
	#region Members
	
	private Dictionary<string, UnityEngine.Object> m_dicRes = new Dictionary<string, UnityEngine.Object>();
	
	#endregion
}

